
// in js there are two types of memory
// 1> Stack memory &
// 2> Heap memory

// ##########     1> Stack Memories     #######################

let Myyoutubename= "Vishal.com"

let Anotheryoutubrname= Myyoutubename  //Vishal.com
 Anotheryoutubename ="Shubham.com"

console.log(Myyoutubename);
console.log(Anotheryoutubrname);
console.log(Anotheryoutubename);  // copy generated by myyoutubename but value can be changed i.e "Shubham.com" i.e STACK MEMORY 


//  ############  HEAP MEMORY  ####################

let Myname={

    name:"vishal",
    email:"Vishal@gmail.com" ,
    number:9834181510n

}

console.log(Myname)

let Newname = Myname
Newname.email="deshmukh.gmailcom"            //USING OBJECT REFRENCE TO CHANE THE EMAIL ("deshmukh.gmailcom") I.E HEAP MEMORY ORIGINAL VALUE CHANGE TO NEW VALUE
console.log(Newname)